<figure>
    <center>
    <img src="../../figures/kinki2.png"  width="400" height="370" align="center"/>
    </center>
</figure>

# <span style="color:blue"><center>Hackathon: Shinkansen Travel Experience</center></span>

# <span style="color:red"><center>Data consolidation</center></span>

## <span style="color:green"><center>Merging Survey and Travel Data</center></span>

## <span style="color:blue">Authors</span>

1. Daniel Mauricio Montenegro Reyes, dextronomo@gmail.com
1. Juan Felipe Contreras Alc√≠var, j.contrerasa94@gmail.com

## <span style="color:blue">References</span>

1. [Ref to Link](link here)

## <span style="color:blue">Libraries Used</span>

In [1]:
import pandas as pd

## <span style="color:blue">Read Train Survey</span>

In [2]:
survey_df_train = pd.read_csv('../../input/train/raw/Surveydata_train_(2).csv')
survey_df_train

,ID,Overall_Experience,Seat_Comfort,Seat_Class,Arrival_Time_Convenient,Catering,Platform_Location,Onboard_Wifi_Service,Onboard_Entertainment,Online_Support,Ease_of_Online_Booking,Onboard_Service,Legroom,Baggage_Handling,CheckIn_Service,Cleanliness,Online_Boarding
0,98800001,0,Needs Improvement,Green Car,Excellent,Excellent,Very Convenient,Good,Needs Improvement,Acceptable,Needs Improvement,Needs Improvement,Acceptable,Needs Improvement,Good,Needs Improvement,Poor
1,98800002,0,Poor,Ordinary,Excellent,Poor,Needs Improvement,Good,Poor,Good,Good,Excellent,Needs Improvement,Poor,Needs Improvement,Good,Good
2,98800003,1,Needs Improvement,Green Car,Needs Improvement,Needs Improvement,Needs Improvement,Needs Improvement,Good,Excellent,Excellent,Excellent,Excellent,Excellent,Good,Excellent,Excellent
3,98800004,0,Acceptable,Ordinary,Needs Improvement,NaN,Needs Improvement,Acceptable,Needs Improvement,Acceptable,Acceptable,Acceptable,Acceptable,Acceptable,Good,Acceptable,Acceptable
4,98800005,1,Acceptable,Ordinary,Acceptable,Acceptable,Manageable,Needs Improvement,Good,Excellent,Good,Good,Good,Good,Good,Good,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94374,98894375,0,Poor,Ordinary,Good,Good,Convenient,Poor,Poor,Poor,Poor,Good,Good,Good,Needs Improvement,Good,Poor
94375,98894376,1,Good,Ordinary,Good,Good,Convenient,Needs Improvement,Excellent,Excellent,Acceptable,Acceptable,Acceptable,Acceptable,Good,Acceptable,Good
94376,98894377,1,Needs Improvement,Green Car,Needs Improvement,Needs Improvement,Needs Improvement,Good,Excellent,Good,Good,Good,Good,Good,Acceptable,Good,Acceptable
94377,98894378,0,Needs Improvement,Ordinary,NaN,Needs Improvement,Convenient,Good,Needs Improvement,Good,Good,Acceptable,Good,Good,Good,Excellent,Good
94378,98894379,0,Acceptable,Ordinary,Poor,Acceptable,Manageable,Acceptable,Acceptable,Acceptable,Acceptable,Poor,Good,Good,Poor,Good,Acceptable

## <span style="color:blue">Read Train Travel Data</span>

In [3]:
travel_df_train = pd.read_csv('../../input/train/raw/Traveldata_train_(2).csv')
travel_df_train

,ID,Gender,Customer_Type,Age,Type_Travel,Travel_Class,Travel_Distance,Departure_Delay_in_Mins,Arrival_Delay_in_Mins
0,98800001,Female,Loyal Customer,52.0,NaN,Business,272,0.0,5.0
1,98800002,Male,Loyal Customer,48.0,Personal Travel,Eco,2200,9.0,0.0
2,98800003,Female,Loyal Customer,43.0,Business Travel,Business,1061,77.0,119.0
3,98800004,Female,Loyal Customer,44.0,Business Travel,Business,780,13.0,18.0
4,98800005,Female,Loyal Customer,50.0,Business Travel,Business,1981,0.0,0.0
...,...,...,...,...,...,...,...,...,...
94374,98894375,Male,Loyal Customer,32.0,Business Travel,Business,1357,83.0,125.0
94375,98894376,Male,Loyal Customer,44.0,Business Travel,Business,592,5.0,11.0
94376,98894377,Male,NaN,63.0,Business Travel,Business,2794,0.0,0.0
94377,98894378,Male,Loyal Customer,16.0,Personal Travel,Eco,2744,0.0,0.0
94378,98894379,Male,Loyal Customer,54.0,NaN,Eco,2107,28.0,28.0

## <span style="color:blue">Read Train Travel Data</span>

In [4]:
df_train = pd.merge(survey_df_train, travel_df_train, on='ID', how='outer')

In [5]:
df_train

,ID,Overall_Experience,Seat_Comfort,Seat_Class,Arrival_Time_Convenient,Catering,Platform_Location,Onboard_Wifi_Service,Onboard_Entertainment,Online_Support,...,Cleanliness,Online_Boarding,Gender,Customer_Type,Age,Type_Travel,Travel_Class,Travel_Distance,Departure_Delay_in_Mins,Arrival_Delay_in_Mins
0,98800001,0,Needs Improvement,Green Car,Excellent,Excellent,Very Convenient,Good,Needs Improvement,Acceptable,...,Needs Improvement,Poor,Female,Loyal Customer,52.0,NaN,Business,272,0.0,5.0
1,98800002,0,Poor,Ordinary,Excellent,Poor,Needs Improvement,Good,Poor,Good,...,Good,Good,Male,Loyal Customer,48.0,Personal Travel,Eco,2200,9.0,0.0
2,98800003,1,Needs Improvement,Green Car,Needs Improvement,Needs Improvement,Needs Improvement,Needs Improvement,Good,Excellent,...,Excellent,Excellent,Female,Loyal Customer,43.0,Business Travel,Business,1061,77.0,119.0
3,98800004,0,Acceptable,Ordinary,Needs Improvement,NaN,Needs Improvement,Acceptable,Needs Improvement,Acceptable,...,Acceptable,Acceptable,Female,Loyal Customer,44.0,Business Travel,Business,780,13.0,18.0
4,98800005,1,Acceptable,Ordinary,Acceptable,Acceptable,Manageable,Needs Improvement,Good,Excellent,...,Good,Good,Female,Loyal Customer,50.0,Business Travel,Business,1981,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94374,98894375,0,Poor,Ordinary,Good,Good,Convenient,Poor,Poor,Poor,...,Good,Poor,Male,Loyal Customer,32.0,Business Travel,Business,1357,83.0,125.0
94375,98894376,1,Good,Ordinary,Good,Good,Convenient,Needs Improvement,Excellent,Excellent,...,Acceptable,Good,Male,Loyal Customer,44.0,Business Travel,Business,592,5.0,11.0
94376,98894377,1,Needs Improvement,Green Car,Needs Improvement,Needs Improvement,Needs Improvement,Good,Excellent,Good,...,Good,Acceptable,Male,NaN,63.0,Business Travel,Business,2794,0.0,0.0
94377,98894378,0,Needs Improvement,Ordinary,NaN,Needs Improvement,Convenient,Good,Needs Improvement,Good,...,Excellent,Good,Male,Loyal Customer,16.0,Personal Travel,Eco,2744,0.0,0.0
94378,98894379,0,Acceptable,Ordinary,Poor,Acceptable,Manageable,Acceptable,Acceptable,Acceptable,...,Good,Acceptable,Male,Loyal Customer,54.0,NaN,Eco,2107,28.0,28.0

## <span style="color:blue">Save Merged Data</span>

In [6]:
df_train.to_csv('../../input/train/merged/train_merged.csv', sep=';', index=False)

## <span style="color:blue">Automation</span>

Automation of merging data

In [7]:
import os
import pandas as pd
from glob import glob

class DataModel:
    def __init__(self, train_path: str, test_path: str):
        self.train_path = train_path
        self.test_path = test_path

    def create_merge_folders(self):
        root_train = "/".join(self.train_path.split("/")[:-2])
        self.path_train_merged = root_train + "/merged"
        
        root_test = "/".join(self.test_path.split("/")[:-2])
        self.path_test_merged = root_test + "/merged"
        
        os.makedirs(self.path_train_merged, exist_ok=True)
        os.makedirs(self.path_test_merged, exist_ok=True)

    def get_data_files(self, format_type):
        self.train_files = glob(self.train_path + f"*.{format_type}")
        self.test_files = glob(self.test_path + f"*.{format_type}")
    
    def merge_train_test(self, on="ID", how="outer"):
        self.df_train = pd.DataFrame([], columns=[on])
        self.df_test  = pd.DataFrame([], columns=[on])
        
        for train_file in self.train_files:
            temp_df = pd.read_csv(train_file)
            self.df_train = pd.merge(self.df_train, temp_df, on=on, how=how)

        for test_file in self.test_files:
            temp_df = pd.read_csv(test_file)
            self.df_test = pd.merge(self.df_test, temp_df, on=on, how=how)

    def save_merged_data(self, name_train, name_test):
        self.df_train.to_csv(self.path_train_merged + f"/{name_train}", sep=";", index=None)
        self.df_test.to_csv(self.path_test_merged + f"/{name_test}", sep=";", index=None)

    def merge_data(self):

        ## PARAMS ##
        format_type="csv"
        on="ID"
        how="outer"
        name_train="train_merged.csv"
        name_test="test_merged.csv"

        ### PIPELINE ###
        self.create_merge_folders()
        self.get_data_files(format_type=format_type)
        self.merge_train_test(on=on, how=how)
        self.save_merged_data(name_train=name_train, name_test=name_test)

## <span style="color:blue">Using Automation</span>

In [8]:
train_path = '../../input/train/raw/'
test_path = '../../input/test/raw/'

data = DataModel(train_path=train_path, test_path=test_path)
data.merge_data()

## <span style="color:blue">Using Automation From src</span>

In [9]:
import sys
sys.path.append("../../src/")

from DataModel import DataModel

train_path = '../../input/train/raw/'
test_path = '../../input/test/raw/'

data = DataModel(train_path=train_path, test_path=test_path)
data.merge_data()